language: generic

sudo: required

services:
    - docker 
    
before_install:
    - docker build -t marcfefischer/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true marcfefischer/react-test npm test

after_success:
    - docker build -t marcfefischer/multi-client ./client
    - docker build -t marcfefischer/multi-nginx ./nginx
    - docker build -t marcfefischer/multi-server ./server
    - docker build -t marcfefischer/multi-worker ./worker
    # login to docker Hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push those images to docker Hub
    - docker push marcfefischer/multi-client
    - docker push marcfefischer/multi-nginx
    - docker push marcfefischer/multi-server
    - docker push marcfefischer/multi-worker 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env-1
    bucket_name: elasticbeanstalk-us-west-2-633420010155
    buckit-path: multi-docker
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    access_secret_key: $AWS_SECRET_KEY
